"""init

Revision ID: 1d8f6658207c
Revises: e00ad2030b1e
Create Date: 2026-09-23 11:25:37.015940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d8f6658207c'
down_revision: Union[str, None] = 'e00ad2030b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###