"""init patient_groups, users and likes

Revision ID: e00ad2030b1e
Revises: 465c7ac23f81
Create Date: 2026-09-23 10:27:26.698413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00ad2030b1e'
down_revision: Union[str, None] = '465c7ac23f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###